### ISSUE TITLE
how to set T_BS in camera yaml  setting file

### ISSUE THREAD

**Issue by winf** [jiawei-mo/dsvo#1]
@jiawei-mo could you shared these two files ," $(env HOME)/workspace/data/cams/kitti/cam0.yaml"  "$(env HOME)/workspace/data/cams/kitti/cam1.yaml" . Thankyou very much.

**Comment by jiawei-mo** [comment]
Hi, thank you for interested in my project. Here is a [link](https://drive.google.com/open?id=14d7wK6QyGRZHCxDyhhjuaaSGoLBah7zz) to some datasets and calibration data. We did not test on kitti dataset, however, you can create your own calibration files by following this [link](https://github.com/ethz-asl/kalibr/wiki/yaml-formats).
